-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 22:05:53 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `username` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(25) NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidoPaterno` VARCHAR(45) NULL,
  `apellidoMaterno` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `colonia` VARCHAR(45) NULL,
  `cp` INT NULL,
  `ciudad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulo` (
  `idarticulo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(140) NULL,
  `director` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `temporada` INT NULL,
  `fecha` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `cover` VARCHAR(100) NULL,
  `tipoArticulo` VARCHAR(1) NULL,
  PRIMARY KEY (`idarticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarjetaDeCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarjetaDeCredito` (
  `numero` VARCHAR(16) NOT NULL,
  `banco` VARCHAR(45) NULL,
  `numeroDeConfirmacion` VARCHAR(10) NULL,
  `vigencia` DATE NULL,
  `usuario_username` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_tarjetaDeCredito_usuario1_idx` (`usuario_username` ASC),
  CONSTRAINT `fk_tarjetaDeCredito_usuario1`
    FOREIGN KEY (`usuario_username`)
    REFERENCES `mydb`.`usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carritoDeCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carritoDeCompra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NULL,
  `usuario_username` VARCHAR(25) NOT NULL,
  `articulo_idarticulo` VARCHAR(10) NOT NULL,
  `tarjetaDeCredito_numero` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_carritoDeCompra_usuario_idx` (`usuario_username` ASC),
  INDEX `fk_carritoDeCompra_articulo1_idx` (`articulo_idarticulo` ASC),
  INDEX `fk_carritoDeCompra_tarjetaDeCredito1_idx` (`tarjetaDeCredito_numero` ASC),
  CONSTRAINT `fk_carritoDeCompra_usuario`
    FOREIGN KEY (`usuario_username`)
    REFERENCES `mydb`.`usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carritoDeCompra_articulo1`
    FOREIGN KEY (`articulo_idarticulo`)
    REFERENCES `mydb`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carritoDeCompra_tarjetaDeCredito1`
    FOREIGN KEY (`tarjetaDeCredito_numero`)
    REFERENCES `mydb`.`tarjetaDeCredito` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
